using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Common.Constants
{
    public enum TextEmotes
    {
        EMOTE_AGREE = 1,
        EMOTE_AMAZE = 2,
        EMOTE_ANGRY = 3,
        EMOTE_APOLOGIZE = 4,
        EMOTE_APPLAUD = 5,
        EMOTE_BARK = 205,
        EMOTE_BASHFUL = 6,
        EMOTE_BECKON = 7,
        EMOTE_BEG = 8,
        EMOTE_BITE = 9,
        EMOTE_BLEED = 10,
        EMOTE_BLINK = 11,
        EMOTE_BLUSH = 12,
        EMOTE_BOGGLE = 107,
        EMOTE_BONK = 13,
        EMOTE_BORED = 14,
        EMOTE_BOUNCE = 15,
        EMOTE_BOW = 17,
        EMOTE_BRB = 16,
        EMOTE_BURP = 18,
        EMOTE_BYE = 19,
        EMOTE_CACKLE = 20,
        EMOTE_CALM = 108,
        EMOTE_CHEER = 21,
        EMOTE_CHICKEN = 22,
        EMOTE_CHUCKLE = 23,
        EMOTE_CLAP = 24,
        EMOTE_COLD = 109,
        EMOTE_COMFORT = 110,
        EMOTE_COMMEND = 243,
        EMOTE_CONFUSED = 25,
        EMOTE_CONGRATULATE = 26,
        EMOTE_COUGH = 27,
        EMOTE_COWER = 28,
        EMOTE_CRACK = 29,
        EMOTE_CRINGE = 30,
        EMOTE_CRY = 31,
        EMOTE_CUDDLE = 111,
        EMOTE_CURIOUS = 32,
        EMOTE_CURTSEY = 33,
        EMOTE_DANCE = 34,
        EMOTE_DRINK = 35,
        EMOTE_DROOL = 36,
        EMOTE_DUCK = 112,
        EMOTE_EAT = 37,
        EMOTE_EYE = 38,
        EMOTE_FART = 39,
        EMOTE_FIDGET = 40,
        EMOTE_FLEX = 41,
        EMOTE_FLOP = 224,
        EMOTE_FROWN = 42,
        EMOTE_GASP = 43,
        EMOTE_GAZE = 44,
        EMOTE_GIGGLE = 45,
        EMOTE_GLARE = 46,
        EMOTE_GLOAT = 47,
        EMOTE_GREET = 48,
        EMOTE_GRIN = 49,
        EMOTE_GROAN = 50,
        EMOTE_GROVEL = 51,
        EMOTE_GROWL = 204,
        EMOTE_GUFFAW = 52,
        EMOTE_HAIL = 53,
        EMOTE_HAPPY = 54,
        EMOTE_HELLO = 55,
        EMOTE_HUG = 56,
        EMOTE_HUNGRY = 57,
        EMOTE_INSULT = 113,
        EMOTE_INTRODUCE = 114,
        EMOTE_JK = 115,
        EMOTE_KISS = 58,
        EMOTE_KNEEL = 59,
        EMOTE_LAUGH = 60,
        EMOTE_LAYDOWN = 61,
        EMOTE_LICK = 116,
        EMOTE_LISTEN = 117,
        EMOTE_LOST = 118,
        EMOTE_LOVE = 225,
        EMOTE_MASSAGE = 62,
        EMOTE_MOAN = 63,
        EMOTE_MOCK = 119,
        EMOTE_MOO = 226,
        EMOTE_MOON = 64,
        EMOTE_MOURN = 65,
        EMOTE_NO = 66,
        EMOTE_NOD = 67,
        EMOTE_NOSEPICK = 68,
        EMOTE_PANIC = 69,
        EMOTE_PEER = 70,
        EMOTE_PITY = 203,
        EMOTE_PLEAD = 71,
        EMOTE_POINT = 72,
        EMOTE_POKE = 73,
        EMOTE_PONDER = 120,
        EMOTE_POUNCE = 121,
        EMOTE_PRAISE = 122,
        EMOTE_PRAY = 74,
        EMOTE_PURR = 123,
        EMOTE_PUZZLE = 124,
        EMOTE_RAISE = 125,
        EMOTE_RASP = 183,
        EMOTE_READY = 126,
        EMOTE_ROAR = 75,
        EMOTE_ROFL = 76,
        EMOTE_RUDE = 77,
        EMOTE_SALUTE = 78,
        EMOTE_SCARED = 223,
        EMOTE_SCRATCH = 79,
        EMOTE_SEXY = 80,
        EMOTE_SHAKE = 81,
        EMOTE_SHIMMY = 127,
        EMOTE_SHIVER = 128,
        EMOTE_SHOO = 129,
        EMOTE_SHOUT = 82,
        EMOTE_SHRUG = 83,
        EMOTE_SHY = 84,
        EMOTE_SIGH = 85,
        EMOTE_SIT = 86,
        EMOTE_SLAP = 130,
        EMOTE_SLEEP = 87,
        EMOTE_SMILE = 163,
        EMOTE_SMIRK = 131,
        EMOTE_SNARL = 88,
        EMOTE_SNICKER = 140,
        EMOTE_SNIFF = 132,
        EMOTE_SNUB = 133,
        EMOTE_SOOTHE = 134,
        EMOTE_SPIT = 89,
        EMOTE_STAND = 141,
        EMOTE_STARE = 90,
        EMOTE_STINK = 135,
        EMOTE_SURPRISED = 91,
        EMOTE_SURRENDER = 92,
        EMOTE_TALK = 93,
        EMOTE_TALKEX = 94,
        EMOTE_TALKQ = 95,
        EMOTE_TAP = 96,
        EMOTE_TAUNT = 136,
        EMOTE_TEASE = 137,
        EMOTE_THANK = 97,
        EMOTE_THIRSTY = 138,
        EMOTE_THREATEN = 98,
        EMOTE_TICKLE = 142,
        EMOTE_TIRED = 99,
        EMOTE_TRAIN = 264,
        EMOTE_VETO = 139,
        EMOTE_VICTORY = 100,
        EMOTE_VIOLIN = 143,
        EMOTE_WAVE = 101,
        EMOTE_WELCOME = 102,
        EMOTE_WHINE = 103,
        EMOTE_WHISTLE = 104,
        EMOTE_WORK = 105,
        EMOTE_YAWN = 106,
    }

    public static class Emotes
    {
        private static readonly Dictionary<TextEmotes, uint> emoteLookup = new Dictionary<TextEmotes, uint>()
        {
            { TextEmotes.EMOTE_AGREE, 0 },
            { TextEmotes.EMOTE_AMAZE, 0 },
            { TextEmotes.EMOTE_ANGRY, 14 },
            { TextEmotes.EMOTE_APOLOGIZE, 0 },
            { TextEmotes.EMOTE_APPLAUD, 21 },
            { TextEmotes.EMOTE_BARK, 0 },
            { TextEmotes.EMOTE_BASHFUL, 24 },
            { TextEmotes.EMOTE_BECKON, 0 },
            { TextEmotes.EMOTE_BEG, 20 },
            { TextEmotes.EMOTE_BITE, 0 },
            { TextEmotes.EMOTE_BLEED, 0 },
            { TextEmotes.EMOTE_BLINK, 0 },
            { TextEmotes.EMOTE_BLUSH, 24 },
            { TextEmotes.EMOTE_BOGGLE, 6 },
            { TextEmotes.EMOTE_BONK, 0 },
            { TextEmotes.EMOTE_BORED, 0 },
            { TextEmotes.EMOTE_BOUNCE, 0 },
            { TextEmotes.EMOTE_BOW, 2 },
            { TextEmotes.EMOTE_BRB, 0 },
            { TextEmotes.EMOTE_BURP, 0 },
            { TextEmotes.EMOTE_BYE, 3 },
            { TextEmotes.EMOTE_CACKLE, 11 },
            { TextEmotes.EMOTE_CALM, 0 },
            { TextEmotes.EMOTE_CHEER, 4 },
            { TextEmotes.EMOTE_CHICKEN, 19 },
            { TextEmotes.EMOTE_CHUCKLE, 11 },
            { TextEmotes.EMOTE_CLAP, 21 },
            { TextEmotes.EMOTE_COLD, 0 },
            { TextEmotes.EMOTE_COMFORT, 0 },
            { TextEmotes.EMOTE_COMMEND, 21 },
            { TextEmotes.EMOTE_CONFUSED, 6 },
            { TextEmotes.EMOTE_CONGRATULATE, 21 },
            { TextEmotes.EMOTE_COUGH, 0 },
            { TextEmotes.EMOTE_COWER, 0 },
            { TextEmotes.EMOTE_CRACK, 0 },
            { TextEmotes.EMOTE_CRINGE, 0 },
            { TextEmotes.EMOTE_CRY, 18 },
            { TextEmotes.EMOTE_CUDDLE, 0 },
            { TextEmotes.EMOTE_CURIOUS, 6 },
            { TextEmotes.EMOTE_CURTSEY, 2 },
            { TextEmotes.EMOTE_DANCE, 10 },
            { TextEmotes.EMOTE_DRINK, 7 },
            { TextEmotes.EMOTE_DROOL, 0 },
            { TextEmotes.EMOTE_DUCK, 0 },
            { TextEmotes.EMOTE_EAT, 7 },
            { TextEmotes.EMOTE_EYE, 0 },
            { TextEmotes.EMOTE_FART, 0 },
            { TextEmotes.EMOTE_FIDGET, 0 },
            { TextEmotes.EMOTE_FLEX, 23 },
            { TextEmotes.EMOTE_FLOP, 0 },
            { TextEmotes.EMOTE_FROWN, 0 },
            { TextEmotes.EMOTE_GASP, 5 },
            { TextEmotes.EMOTE_GAZE, 0 },
            { TextEmotes.EMOTE_GIGGLE, 11 },
            { TextEmotes.EMOTE_GLARE, 0 },
            { TextEmotes.EMOTE_GLOAT, 11 },
            { TextEmotes.EMOTE_GREET, 3 },
            { TextEmotes.EMOTE_GRIN, 0 },
            { TextEmotes.EMOTE_GROAN, 0 },
            { TextEmotes.EMOTE_GROVEL, 20 },
            { TextEmotes.EMOTE_GROWL, 15 },
            { TextEmotes.EMOTE_GUFFAW, 11 },
            { TextEmotes.EMOTE_HAIL, 3 },
            { TextEmotes.EMOTE_HAPPY, 0 },
            { TextEmotes.EMOTE_HELLO, 3 },
            { TextEmotes.EMOTE_HUG, 0 },
            { TextEmotes.EMOTE_HUNGRY, 0 },
            { TextEmotes.EMOTE_INSULT, 14 },
            { TextEmotes.EMOTE_INTRODUCE, 0 },
            { TextEmotes.EMOTE_JK, 0 },
            { TextEmotes.EMOTE_KISS, 17 },
            { TextEmotes.EMOTE_KNEEL, 68 },
            { TextEmotes.EMOTE_LAUGH, 11 },
            { TextEmotes.EMOTE_LAYDOWN, 12 },
            { TextEmotes.EMOTE_LICK, 0 },
            { TextEmotes.EMOTE_LISTEN, 0 },
            { TextEmotes.EMOTE_LOST, 6 },
            { TextEmotes.EMOTE_LOVE, 0 },
            { TextEmotes.EMOTE_MASSAGE, 0 },
            { TextEmotes.EMOTE_MOAN, 0 },
            { TextEmotes.EMOTE_MOCK, 0 },
            { TextEmotes.EMOTE_MOO, 0 },
            { TextEmotes.EMOTE_MOON, 0 },
            { TextEmotes.EMOTE_MOURN, 18 },
            { TextEmotes.EMOTE_NO, 274 },
            { TextEmotes.EMOTE_NOD, 273 },
            { TextEmotes.EMOTE_NOSEPICK, 0 },
            { TextEmotes.EMOTE_PANIC, 0 },
            { TextEmotes.EMOTE_PEER, 0 },
            { TextEmotes.EMOTE_PITY, 0 },
            { TextEmotes.EMOTE_PLEAD, 20 },
            { TextEmotes.EMOTE_POINT, 25 },
            { TextEmotes.EMOTE_POKE, 0 },
            { TextEmotes.EMOTE_PONDER, 6 },
            { TextEmotes.EMOTE_POUNCE, 0 },
            { TextEmotes.EMOTE_PRAISE, 0 },
            { TextEmotes.EMOTE_PRAY, 16 },
            { TextEmotes.EMOTE_PURR, 0 },
            { TextEmotes.EMOTE_PUZZLE, 6 },
            { TextEmotes.EMOTE_RAISE, 0 },
            { TextEmotes.EMOTE_RASP, 14 },
            { TextEmotes.EMOTE_READY, 0 },
            { TextEmotes.EMOTE_ROAR, 15 },
            { TextEmotes.EMOTE_ROFL, 11 },
            { TextEmotes.EMOTE_RUDE, 14 },
            { TextEmotes.EMOTE_SALUTE, 66 },
            { TextEmotes.EMOTE_SCARED, 0 },
            { TextEmotes.EMOTE_SCRATCH, 0 },
            { TextEmotes.EMOTE_SEXY, 0 },
            { TextEmotes.EMOTE_SHAKE, 0 },
            { TextEmotes.EMOTE_SHIMMY, 0 },
            { TextEmotes.EMOTE_SHIVER, 0 },
            { TextEmotes.EMOTE_SHOO, 0 },
            { TextEmotes.EMOTE_SHOUT, 22 },
            { TextEmotes.EMOTE_SHRUG, 6 },
            { TextEmotes.EMOTE_SHY, 24 },
            { TextEmotes.EMOTE_SIGH, 0 },
            { TextEmotes.EMOTE_SIT, 13 },
            { TextEmotes.EMOTE_SLAP, 0 },
            { TextEmotes.EMOTE_SLEEP, 12 },
            { TextEmotes.EMOTE_SMILE, 0 },
            { TextEmotes.EMOTE_SMIRK, 0 },
            { TextEmotes.EMOTE_SNARL, 0 },
            { TextEmotes.EMOTE_SNICKER, 0 },
            { TextEmotes.EMOTE_SNIFF, 0 },
            { TextEmotes.EMOTE_SNUB, 0 },
            { TextEmotes.EMOTE_SOOTHE, 0 },
            { TextEmotes.EMOTE_SPIT, 0 },
            { TextEmotes.EMOTE_STAND, 26 },
            { TextEmotes.EMOTE_STARE, 0 },
            { TextEmotes.EMOTE_STINK, 0 },
            { TextEmotes.EMOTE_SURPRISED, 0 },
            { TextEmotes.EMOTE_SURRENDER, 20 },
            { TextEmotes.EMOTE_TALK, 1 },
            { TextEmotes.EMOTE_TALKEX, 5 },
            { TextEmotes.EMOTE_TALKQ, 6 },
            { TextEmotes.EMOTE_TAP, 0 },
            { TextEmotes.EMOTE_TAUNT, 19 },
            { TextEmotes.EMOTE_TEASE, 0 },
            { TextEmotes.EMOTE_THANK, 0 },
            { TextEmotes.EMOTE_THIRSTY, 0 },
            { TextEmotes.EMOTE_THREATEN, 0 },
            { TextEmotes.EMOTE_TICKLE, 0 },
            { TextEmotes.EMOTE_TIRED, 0 },
            { TextEmotes.EMOTE_TRAIN, 275 },
            { TextEmotes.EMOTE_VETO, 0 },
            { TextEmotes.EMOTE_VICTORY, 4 },
            { TextEmotes.EMOTE_VIOLIN, 18 },
            { TextEmotes.EMOTE_WAVE, 3 },
            { TextEmotes.EMOTE_WELCOME, 3 },
            { TextEmotes.EMOTE_WHINE, 0 },
            { TextEmotes.EMOTE_WHISTLE, 0 },
            { TextEmotes.EMOTE_WORK, 0 },
            { TextEmotes.EMOTE_YAWN, 0 },
        };

        public static uint Get(TextEmotes emote) => emoteLookup.ContainsKey(emote) ? emoteLookup[emote] : 0;
    }


}
