public enum Opcodes : ushort
{
    SMSG_AUTH_CHALLENGE,
    SMSG_AUTH_RESPONSE,
    CMSG_AUTH_SESSION,
    CMSG_CHAR_CREATE,
    SMSG_CHAR_CREATE,
    CMSG_CHAR_DELETE,
    SMSG_CHAR_DELETE,
    CMSG_CHAR_ENUM,
    SMSG_CHAR_ENUM,
    CMSG_PING,
    SMSG_PONG,
    CMSG_PLAYER_LOGIN,
    SMSG_UPDATE_OBJECT,
    CMSG_QUERY_TIME,
    SMSG_LOGIN_SETTIMESPEED,

    // NameCache,
    CMSG_NAME_QUERY,
    SMSG_NAME_QUERY_RESPONSE,

    // Logout,
    CMSG_LOGOUT_REQUEST,
    SMSG_LOGOUT_COMPLETE,

    // Teleport,
    CMSG_WORLD_TELEPORT,
    SMSG_NEW_WORLD,
    SMSG_TRANSFER_PENDING,

    // Chat
    CMSG_MESSAGECHAT,
    SMSG_MESSAGECHAT,
    CMSG_TEXT_EMOTE,
    SMSG_TEXT_EMOTE,
    SMSG_EMOTE,

    // Movement,
    MSG_MOVE_START_FORWARD,
    MSG_MOVE_START_BACKWARD,
    MSG_MOVE_STOP,
    MSG_MOVE_START_STRAFE_LEFT,
    MSG_MOVE_START_STRAFE_RIGHT,
    MSG_MOVE_STOP_STRAFE,
    MSG_MOVE_JUMP,
    MSG_MOVE_START_TURN_LEFT,
    MSG_MOVE_START_TURN_RIGHT,
    MSG_MOVE_STOP_TURN,
    MSG_MOVE_START_PITCH_UP,
    MSG_MOVE_START_PITCH_DOWN,
    MSG_MOVE_STOP_PITCH,
    MSG_MOVE_SET_RUN_MODE,
    MSG_MOVE_SET_WALK_MODE,
    MOVE_COLLIDE_REDIRECT,
    MOVE_COLLIDE_STUCK,
    MSG_MOVE_START_SWIM,
    MSG_MOVE_STOP_SWIM,
    MSG_MOVE_SET_FACING,
    MSG_MOVE_SET_PITCH,
    MSG_MOVE_ROOT,
    MSG_MOVE_UNROOT,
    MSG_MOVE_HEARTBEAT,
    MSG_MOVE_FALL_LAND,
    MSG_MOVE_START_ASCEND,
    MSG_MOVE_STOP_ASCEND,

    // Force speed change
    SMSG_FORCE_SPEED_CHANGE,
    SMSG_FORCE_SWIM_SPEED_CHANGE,
    SMSG_FORCE_FLIGHT_SPEED_CHANGE,

    // Flight
    SMSG_MOVE_SET_CAN_FLY,
    SMSG_MOVE_UNSET_CAN_FLY,

    // Worldporting
    SMSG_MOVE_WORLDPORT_ACK,
    MSG_MOVE_WORLDPORT_ACK,
    MSG_MOVE_TELEPORT_ACK,
    CMSG_AREATRIGGER,
    CMSG_ZONEUPDATE,

    // Standstate
    CMSG_STANDSTATECHANGE,

    // Misc
    SMSG_LOGIN_VERIFY_WORLD,
    SMSG_TUTORIAL_FLAGS,
    SMSG_ACCOUNT_DATA_MD5,
    SMSG_UI_CONFIG_MD5,
    CMSG_UPDATE_ACCOUNT_DATA,
    SMSG_UPDATE_ACCOUNT_DATA,
    SMSG_TIME_SYNC_REQ,
    SMSG_INITIAL_SPELLS,
    SMSG_ADDON_INFO,
    MSG_VERIFY_CONNECTIVITY
}
