//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45,1688.99,1053.48,18.6775,0.00117,189,Scarlet Monastery - Graveyard Entrance,0
        ///78,-16.4,-383.07,61.78,1.86,36,DeadMines,0
        ///101,54.23,0.28,-18.34,6.26,34,Stormwind Stockades,0
        ///104,-8764.83,846.075,87.4842,3.77934,0,Stormwind Stockades - Outside,0
        ///107,-0.91,40.57,-24.23,0,35,Stormwind Vault,0
        ///109,-8653.45,606.19,91.16,0,0,Stormwind Vault Instance,0
        ///119,-11208.3,1672.52,24.66,4.55217,0,Deadmines - Outside Start,0
        ///121,-11339.4,1571.16,100.56,0,0,Deadmines - Outside End,0
        ///145,-229.135,2109.18,76.8898,1.2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AreaTriggers {
            get {
                return ResourceManager.GetString("AreaTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned Armory,-2068.19,7463.77,-18.9908,5.21755,530,,2
        ///Abyssal Sands,-7583.58,-3408.81,43.2019,2.47556,1,,0
        ///Access Shaft Zeon,3742.43,2083.64,148.765,6.032,530,,2
        ///Addles Stead,-10964,240.019,28.5578,2.99821,0,,0
        ///Aerie Peak,260.366,-2125.21,119.565,3.18494,0,,0
        ///Aeris Landing,-2059.85,8550.89,24.0587,1.944,530,,2
        ///Agama Gor,-2020.72,-2107.58,91.9626,5.49717,1,,0
        ///Agamand Mills,2799.46,847.549,111.842,0.509892,0,,0
        ///Agmonds End,-7040.08,-3342.15,241.667,0.82338,0,,0
        ///Agol Watha,451.572,-3342.23,119.689 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Worldports {
            get {
                return ResourceManager.GetString("Worldports", resourceCulture);
            }
        }
    }
}
